[package]
name = "docker-client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "*" , features = ['blocking']}
serde_json = "1.0.149"
serde = { version = "1.0", features = ["derive"] }
eframe = "0.33.3"
egui_extras = "0.33.3"
struct_iterable = "0.1.1"
